

development:
  adapter: postgresql
  encoding: unicode
  database: japanese_development
  pool: 5
  username: cbastable
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: japanese_test
  pool: 5
  username: cbastable
  password: